CREATE DATABASE ESCOLA;

USE ESCOLA;

CREATE TABLE ALUNO (
	CODIGO INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(50),
    IDADE INT,
    PRIMARY KEY (CODIGO)
);

CREATE TABLE CURSO (
	CODIGO INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(30),
    SALA INT,
    HORARIO TIME,
    PRIMARY KEY(CODIGO)
);

ALTER TABLE	ALUNO 
	DROP IDADE;
    
ALTER TABLE ALUNO
	ADD IDADE INT;
    
ALTER TABLE ALUNO
	CHANGE IDADE DATA_NASC DATE;
    
CREATE TABLE MATRICULA (
		CODIGO_ALU INT NOT NULL,
        CODIGO_CUR INT NOT NULL,
        PRIMARY KEY (CODIGO_ALU, CODIGO_CUR),
        FOREIGN KEY(CODIGO_ALU) REFERENCES ALUNO (CODIGO),
        FOREIGN KEY(CODIGO_CUR) REFERENCES CURSO (CODIGO)
);