CREATE DATABASE ESCOLA;

USE ESCOLA;

CREATE TABLE ALUNO (
	CODIGO INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(50),
    IDADE INT,
    PRIMARY KEY (CODIGO)
);

CREATE TABLE CURSO (
	CODIGO INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(30),
    SALA INT,
    HORARIO TIME,
    PRIMARY KEY(CODIGO)
);
    