CREATE DATABASE EXEMPLO_AULA;

USE EXEMPLO_AULA;

CREATE TABLE DEPARTAMENTO (
	CODIGO INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(50) NOT NULL,
    LOCALIZACAO VARCHAR(50),
    CODIGOFUNCIONARIOGERENTE INT NOT NULL,
    PRIMARY KEY (CODIGO)
);


CREATE TABLE FUNCIONARIO (
	CODIGO INT NOT NULL AUTO_INCREMENT,
    PRIMEIRONOME VARCHAR(20) NOT NULL,
    SEGUNDONOME VARCHAR(20),
    ULTIMONOME VARCHAR(20) NOT NULL,
    DATANASCI DATE,
    CPF VARCHAR(11) NOT NULL, 
    RG VARCHAR(20), 
    ENDERECO VARCHAR(100),
    CEP VARCHAR(9),
    CIDADE VARCHAR(50),
    FONE VARCHAR(15),
    CODIGODPTO INT NOT NULL,
    FUNCAO VARCHAR(50),
    SALARIO DECIMAL(9,2),
    PRIMARY KEY (CODIGO),
    FOREIGN KEY(CODIGODPTO) REFERENCES DEPARTAMENTO (CODIGO)
);

INSERT INTO DEPARTAMENTO (NOME, LOCALIZACAO, CODIGOFUNCIONARIOGERENTE) VALUES ("Departamento 01", "Localização 01", 2);
INSERT INTO DEPARTAMENTO (NOME, LOCALIZACAO, CODIGOFUNCIONARIOGERENTE) VALUES ("Departamento 02", "Localização 02", 1);
INSERT INTO DEPARTAMENTO (NOME, LOCALIZACAO, CODIGOFUNCIONARIOGERENTE) VALUES ("Departamento 03", "Localização 03", 5);
INSERT INTO DEPARTAMENTO (NOME, LOCALIZACAO, CODIGOFUNCIONARIOGERENTE) VALUES ("Departamento 04", "Localização 04", 15);

INSERT INTO FUNCIONARIO (PRIMEIRONOME, SEGUNDONOME, ULTIMONOME, DATANASCI, CPF, RG, ENDERECO, CEP, CIDADE, FONE, CODIGODPTO, FUNCAO, SALARIO) VALUES ("Funcionario 01", "Sobrenome 01", "Sobrenome 02", "1990-01-01", "", "", "", "", "", "", 1, "Programador", 1500.00);
INSERT INTO FUNCIONARIO (PRIMEIRONOME, SEGUNDONOME, ULTIMONOME, DATANASCI, CPF, RG, ENDERECO, CEP, CIDADE, FONE, CODIGODPTO, FUNCAO, SALARIO) VALUES ("Funcionario 02", "Sobrenome 02", "Sobrenome 12", "1990-02-02", "", "", "", "", "", "", 2, "Analista", 1500.00);
INSERT INTO FUNCIONARIO (PRIMEIRONOME, SEGUNDONOME, ULTIMONOME, DATANASCI, CPF, RG, ENDERECO, CEP, CIDADE, FONE, CODIGODPTO, FUNCAO, SALARIO) VALUES ("Funcionario 03", "Sobrenome 03", "Sobrenome 22", "1990-03-03", "", "", "", "", "", "", 3, "Estagiario", 1500.00);
INSERT INTO FUNCIONARIO (PRIMEIRONOME, SEGUNDONOME, ULTIMONOME, DATANASCI, CPF, RG, ENDERECO, CEP, CIDADE, FONE, CODIGODPTO, FUNCAO, SALARIO) VALUES ("Funcionario 04", "Sobrenome 04", "Sobrenome 32", "1990-04-04", "", "", "", "", "", "", 4, "Telefonista", 1500.00);
INSERT INTO FUNCIONARIO (PRIMEIRONOME, SEGUNDONOME, ULTIMONOME, DATANASCI, CPF, RG, ENDERECO, CEP, CIDADE, FONE, CODIGODPTO, FUNCAO, SALARIO) VALUES ("Funcionario 05", "Sobrenome 05", "Sobrenome 42", "1990-05-05", "", "", "", "", "", "", 2, "Supervisor", 1500.00);

SELECT PRIMEIRONOME, ULTIMONOME FROM FUNCIONARIO ORDER BY ULTIMONOME ASC;

SELECT * FROM FUNCIONARIO ORDER BY CIDADE ASC;

SELECT PRIMEIRONOME FROM FUNCIONARIO WHERE SALARIO > 1000.00 ORDER BY PRIMEIRONOME, SEGUNDONOME, ULTIMONOME;

SELECT DATANASCI, PRIMEIRONOME FROM FUNCIONARIO ORDER BY DATANASCI DESC;

SELECT CIDADE, ULTIMONOME, PRIMEIRONOME, SEGUNDONOME, FONE, ENDERECO FROM FUNCIONARIO ORDER BY CIDADE, ULTIMONOME, PRIMEIRONOME, SEGUNDONOME;

SELECT SUM(SALARIO) FROM FUNCIONARIO;
SELECT SUM(SALARIO) FROM FUNCIONARIO WHERE FUNCAO = "Analista";
SELECT MAX(SALARIO) FROM FUNCIONARIO WHERE FUNCAO = "Analista";
SELECT MIN(SALARIO) FROM FUNCIONARIO;
SELECT AVG(SALARIO) FROM FUNCIONARIO WHERE FUNCAO = "Analista";

SELECT F.PRIMEIRONOME, D.NOME, F.FUNCAO FROM FUNCIONARIO F 
	INNER JOIN DEPARTAMENTO D ON CODIGODPTO = D.CODIGO
    ORDER BY D.NOME, F.FUNCAO, F.PRIMEIRONOME ;
    
SELECT D.NOME AS "Departamento", F.PRIMEIRONOME AS "Gerente"
FROM DEPARTAMENTO D INNER JOIN FUNCIONARIO F ON D.CODIGOFUNCIONARIOGERENTE = F.CODIGO
ORDER BY D.NOME;

SELECT D.NOME AS "Departamento", SUM(F.SALARIO) AS "Total Folha" 
FROM DEPARTAMENTO D INNER JOIN FUNCIONARIO F ON D.CODIGO = F.CODIGODPTO
GROUP BY D.CODIGO 
ORDER BY D.NOME;


