CREATE DATABASE ELEICAO;

USE ELEICAO;

CREATE TABLE PARTIDO (
	COD_PARTIDO INT NOT NULL AUTO_INCREMENT,
    NOME_PARTIDO VARCHAR(50) NOT NULL,
    PRIMARY KEY (COD_PARTIDO)
);

CREATE TABLE CARGO (
	COD_CARGO INT NOT NULL AUTO_INCREMENT,
    NOME_CARGO VARCHAR(50),
    PRIMARY KEY (COD_CARGO)
);

CREATE TABLE CANDIDATO (
	NUM_CANDIDATO INT NOT NULL AUTO_INCREMENT,
    NOME_CANDIDATO VARCHAR(50) NOT NULL,
    COD_CARGO INT NOT NULL,
    COD_PARTIDO INT NOT NULL,
    PRIMARY KEY (NUM_CANDIDATO),
    FOREIGN KEY (COD_CARGO) REFERENCES CARGO (COD_CARGO),
    FOREIGN KEY (COD_PARTIDO) REFERENCES PARTIDO (COD_PARTIDO)
);

CREATE TABLE ZONA_SECAO (
	NUM_ZONA INT NOT NULL,
    NUM_SECAO INT NOT NULL, 
    NOME_ZONA VARCHAR(50) NOT NULL,
    QTD_ELEITORES INT,
    PRIMARY KEY (NUM_ZONA, NUM_SECAO)
);

CREATE TABLE VOTACAO (
	ID INT NOT NULL AUTO_INCREMENT,
	NUM_ZONA INT NOT NULL, 
    NUM_SECAO INT NOT NULL,
    NUM_CANDIDATO INT NOT NULL,
    QTD_VOTOS INT, 
    PRIMARY KEY(ID),
    FOREIGN KEY (NUM_ZONA, NUM_SECAO) REFERENCES ZONA_SECAO(NUM_ZONA, NUM_SECAO),
    FOREIGN KEY (NUM_CANDIDATO) REFERENCES CANDIDATO (NUM_CANDIDATO)
);

ALTER TABLE VOTACAO ADD DATA_VOTACAO DATETIME;
SELECT * FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE TABLE_NAME = 'CANDIDATO';

ALTER TABLE CANDIDATO DROP CONSTRAINT CANDIDATO_IBFK_2;
ALTER TABLE CANDIDATO DROP COLUMN COD_PARTIDO;

CREATE INDEX IDX_NOME_CANDIDATO ON CANDIDATO (NOME_CANDIDATO);
SHOW INDEX FROM CANDIDATO;

INSERT INTO VOTACAO (NUM_ZONA, NUM_SECAO, NUM_CANDIDATO, QTD_VOTOS, DATA_VOTACAO)
	VALUES (5, 10, 555, 1000, "2024-04-16 19:00");
    
INSERT INTO PARTIDO (NOME_PARTIDO) VALUES ("PAFPP");
INSERT INTO CARGO (NOME_CARGO) VALUES ("Presidente");
INSERT INTO ZONA_SECAO (NUM_ZONA, NUM_SECAO, NOME_ZONA, QTD_ELEITORES)
	VALUES (5, 10, "Zona do João", 200);
INSERT INTO CANDIDATO (NUM_CANDIDATO, COD_CARGO, NOME_CANDIDATO)
	VALUES (555, 1, "João da Silva");
INSERT INTO ZONA_SECAO (NUM_ZONA, NUM_SECAO, NOME_ZONA, QTD_ELEITORES)
	values (7, 99, "Zona Teste", 300);

ALTER TABLE CANDIDATO ADD COD_PARTIDO INT;
ALTER TABLE CANDIDATO ADD FOREIGN KEY (COD_PARTIDO) REFERENCES PARTIDO (COD_PARTIDO);

INSERT INTO PARTIDO (COD_PARTIDO, NOME_PARTIDO) VALUES (5, "Partido Novo");
INSERT INTO CANDIDATO (NUM_CANDIDATO, COD_CARGO, COD_PARTIDO, NOME_CANDIDATO)
	VALUES(556, 1, 5, "Douglas Horvath");

SET SQL_SAFE_UPDATES = 0;

UPDATE VOTACAO SET QTD_VOTOS = (QTD_VOTOS * 2) 
	WHERE NUM_CANDIDATO IN (
		SELECT NUM_CANDIDATO FROM CANDIDATO WHERE COD_CARGO = 1 AND COD_PARTIDO = 5
    );
