CREATE DATABASE VENDA;

USE VENDA;

CREATE TABLE VENDEDOR (
	ID INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(50),
    IDADE INT,
    SALARIO DECIMAL(7,2),
    PRIMARY KEY (ID)
);

CREATE TABLE CLIENTE (
	ID INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(50),
    CIDADE VARCHAR(100),
    TIPO VARCHAR(50),
    PRIMARY KEY (ID)
);

CREATE TABLE PRODUTO (
	ID INT NOT NULL AUTO_INCREMENT,
    DESCRICAO VARCHAR(255),
    QTDE_ESTOQUE INT,
    UNIDADE INT,
    PRECO_UNITARIO DECIMAL(7,2),
    PRIMARY KEY (ID)
);

CREATE TABLE PEDIDO (
	NUMERO INT NOT NULL AUTO_INCREMENT,
    CODIGO_CLI INT NOT NULL,
    CODIGO_VEN INT NOT NULL,
    DATA DATE,
    PRIMARY KEY(NUMERO),
    FOREIGN KEY(CODIGO_CLI) REFERENCES CLIENTE (ID),
    FOREIGN KEY(CODIGO_VEN) REFERENCES VENDEDOR (ID)
);

CREATE TABLE ITENS_PEDIDO (
	ID INT NOT NULL AUTO_INCREMENT,
    CODIGO_PED INT NOT NULL,
    CODIGO_PRO INT NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY(CODIGO_PED) REFERENCES PEDIDO (NUMERO),
    FOREIGN KEY(CODIGO_PRO) REFERENCES PRODUTO (ID),
    QUANTIDADE INT,
    VALOR DECIMAL(7,2)
);